### ISSUE TITLE
Tabbed collapsible: open tab shouldn’t be collapsible, should it?

### ISSUE THREAD

**Issue by beep** [filamentgroup/collapsible#80]
On [the collapsible demo page](https://master-origin-collapsible.fgview.com/demo/index.html), the “Tabbed collapsible set” works as intended. However, the open “tab” can be closed, which seems a bit counterintuitive—I wouldn’t expect the active tab could be collapsed. (This seems like a decent distinction to draw between `accordions` and `tabs`, I guess.)

Depending on what y’all think about the merits of this issue, it seems like a potentially easy fix. e.g., changing this

```
if( self.$tabHeader.is( '.' + activeTabClass ) ) {
	deactivateTab( self.$tabHeader );
} else {
	deactivateTab( $tabContainer.find( '.' + activeTabClass ) );
	activateTab( self.$tabHeader );
}

self.toggle();
```

to this:

```
if( !self.$tabHeader.is( '.' + activeTabClass ) ) {
	deactivateTab( $tabContainer.find( '.' + activeTabClass ) );
	activateTab( self.$tabHeader );
	self.toggle();
}
```

produces the desired behavior.

(Opening this as a question for now, unless/until you folks think it’s a bug!)

**Comment by zachleat** [comment]
I’d be open to adding at least an easy declarative data-attribute option for this but as for changing the default, I _think_ we take advantage of this behavior in some places, right @scottjehl? Specifically when tabs turn into hover panels at different breakpoints?

**Comment by scottjehl** [comment]
Hey @zachleat n @beep 

Hmm. I agree that at tab shouldn't be closable when it's playing the role of a tab. To @zachleat's question, I'm not sure if I can think of any cases where this would conflict with expectations or current behavior, but I don't mind the idea of keeping the current behavior as the default, with an opt-in, at least for a release cycle or something. +1
